site_name: lovely 5mm wiki
theme:
  name: material
  palette:
    primary: indigo    # 主色调
    accent: pink      # 强调色

# 可用的主题色：
# red, pink, purple, deep purple, indigo, blue, light blue, 
# cyan, teal, green, light green, lime, yellow, amber, 
# orange, deep orange, brown, grey, blue grey

nav:
  - 首页: index.md
  
site_url: https://github.com/5mm-wiki.io/5mm-wiki.io/
repo_url: https://github.com/Kafka2006/5mm-wiki.io
edit_uri: edit/main/docs/